import type { Product } from "@/types/product";

/**
 * Deterministic fallback catalogue. Used when FakeStoreAPI is unreachable so
 * the page always renders a complete, stable product listing.
 */
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Handcrafted Woven Backpack",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    category: "bags",
    price: 109.95,
    rating: 3.9,
    ratingCount: 120,
    isNew: true,
    fabric: "Woven Cotton",
    occasion: "Casual",
    segment: "Unisex",
    rawMaterials: "Cotton",
    pattern: "Solid",
    work: "Handloom",
    suitableFor: "Daily Use",
    customizable: "No",
  },
  {
    id: 2,
    title: "Slim-Fit Cotton T-Shirt",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    category: "clothing",
    price: 22.3,
    rating: 4.1,
    ratingCount: 259,
    fabric: "Organic Cotton",
    occasion: "Casual",
    segment: "Men",
    rawMaterials: "Cotton",
    pattern: "Solid",
    work: "Flat Knit",
    suitableFor: "Western Wear",
    customizable: "No",
  },
  {
    id: 3,
    title: "Classic Navy Cotton Jacket",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    category: "clothing",
    price: 55.99,
    rating: 2.9,
    ratingCount: 250,
    isOutOfStock: true,
    fabric: "Cotton Twill",
    occasion: "Formal",
    segment: "Men",
    rawMaterials: "Cotton",
    pattern: "Solid",
    work: "Machine Woven",
    suitableFor: "Outerwear",
    customizable: "No",
  },
  {
    id: 4,
    title: "Slim Fit Premium Leather Watch",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    category: "accessories",
    price: 15.99,
    rating: 4.7,
    ratingCount: 430,
    isNew: true,
    fabric: "Leather",
    occasion: "Formal",
    segment: "Men",
    rawMaterials: "Leather",
    pattern: "Solid",
    work: "Hand Stitched",
    suitableFor: "Formal Wear",
    customizable: "Yes",
  },
  {
    id: 5,
    title: "Opalcade Gold-Plated Bracelet",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelery",
    price: 695,
    rating: 3.9,
    ratingCount: 70,
    fabric: "Gold Plated Brass",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Brass",
    pattern: "Solid",
    work: "Polished Finish",
    suitableFor: "Gifting",
    customizable: "No",
  },
  {
    id: 6,
    title: "White & Gold Plated Ergonomic Mouse",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    category: "electronics",
    price: 64,
    rating: 3.3,
    ratingCount: 203,
    fabric: "Matte Plastic",
    occasion: "Daily",
    segment: "Unisex",
    rawMaterials: "Plastic",
    pattern: "Solid",
    work: "Injection Moulded",
    suitableFor: "Work From Home",
    customizable: "No",
  },
  {
    id: 7,
    title: "Faux Suede Snowboard Jacket",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    category: "clothing",
    price: 20.75,
    rating: 2.1,
    ratingCount: 430,
    isOutOfStock: true,
    fabric: "Faux Suede",
    occasion: "Casual",
    segment: "Women",
    rawMaterials: "Polyester",
    pattern: "Solid",
    work: "Panelled",
    suitableFor: "Outerwear",
    customizable: "No",
  },
  {
    id: 8,
    title: "Solid Oak Portable Hard Case",
    image: "https://fakestoreapi.com/img/71IBHvO7uvL._AC_UY879_.jpg",
    category: "accessories",
    price: 39.99,
    rating: 4.7,
    ratingCount: 500,
    fabric: "Oak",
    occasion: "Travel",
    segment: "Unisex",
    rawMaterials: "Wood",
    pattern: "Grain",
    work: "Carved",
    suitableFor: "Travel",
    customizable: "Yes",
  },
  {
    id: 9,
    title: "Rain Manger Coat With Hood",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    category: "clothing",
    price: 39.99,
    rating: 4.7,
    ratingCount: 500,
    fabric: "Wool Blend",
    occasion: "Formal",
    segment: "Women",
    rawMaterials: "Wool",
    pattern: "Solid",
    work: "Tailored",
    suitableFor: "Outerwear",
    customizable: "No",
  },
  {
    id: 10,
    title: "Opalcade Gold-Plated Pendant Necklace",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelery",
    price: 125,
    rating: 4.2,
    ratingCount: 140,
    isNew: true,
    fabric: "Gold Plated Brass",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Brass",
    pattern: "Filigree",
    work: "Polished Finish",
    suitableFor: "Gifting",
    customizable: "No",
  },
  {
    id: 11,
    title: "Handwoven Jute Floor Rug",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    category: "home",
    price: 89.5,
    rating: 3.8,
    ratingCount: 90,
    fabric: "Jute",
    occasion: "Daily",
    segment: "Home",
    rawMaterials: "Jute",
    pattern: "Woven Stripes",
    work: "Handloom",
    suitableFor: "Home Decor",
    customizable: "No",
  },
  {
    id: 12,
    title: "Artisan Ceramic Pour-Over Set",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    category: "home",
    price: 54.5,
    rating: 4.0,
    ratingCount: 110,
    isNew: true,
    fabric: "Glazed Stoneware",
    occasion: "Daily",
    segment: "Home",
    rawMaterials: "Clay",
    pattern: "Speckled",
    work: "Wheel Thrown",
    suitableFor: "Kitchen",
    customizable: "No",
  },
];
