import type { Product } from "@/types/product";

/**
 * Deterministic fallback catalogue. Used when FakeStoreAPI is unreachable so
 * the page always renders a complete, stable product listing.
 * Prices are in INR (₹).
 */
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Handwoven Khadi Cotton Backpack",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    category: "bags",
    price: 2499,
    rating: 3.9,
    ratingCount: 120,
    isNew: true,
    fabric: "Khadi Cotton",
    occasion: "Casual",
    segment: "Unisex",
    rawMaterials: "Cotton",
    pattern: "Solid",
    work: "Handloom",
    suitableFor: "Daily Use",
    customizable: "No",
  },
  {
    id: 2,
    title: "Block Print Jaipuri Cotton Kurta",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    category: "clothing",
    price: 1899,
    rating: 4.1,
    ratingCount: 259,
    fabric: "Jaipuri Cotton",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Cotton",
    pattern: "Block Print",
    work: "Hand Block Printed",
    suitableFor: "Festive Wear",
    customizable: "No",
  },
  {
    id: 3,
    title: "Banarasi Silk Brocade Jacket",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    category: "clothing",
    price: 4599,
    rating: 2.9,
    ratingCount: 250,
    isOutOfStock: true,
    fabric: "Banarasi Silk",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Silk",
    pattern: "Brocade",
    work: "Hand Woven",
    suitableFor: "Festive Wear",
    customizable: "No",
  },
  {
    id: 4,
    title: "Hand Stitched Leather Kolhapuri Watch",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    category: "accessories",
    price: 1599,
    rating: 4.7,
    ratingCount: 430,
    isNew: true,
    fabric: "Leather",
    occasion: "Formal",
    segment: "Men",
    rawMaterials: "Leather",
    pattern: "Solid",
    work: "Hand Stitched",
    suitableFor: "Formal Wear",
    customizable: "Yes",
  },
  {
    id: 5,
    title: "Kundan Gold-Plated Temple Bracelet",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelery",
    price: 2899,
    rating: 3.9,
    ratingCount: 70,
    fabric: "Gold Plated Brass",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Brass",
    pattern: "Temple Work",
    work: "Polished Finish",
    suitableFor: "Gifting",
    customizable: "No",
  },
  {
    id: 6,
    title: "Channapatna Handcrafted Wooden Pen Stand",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    category: "home",
    price: 899,
    rating: 3.3,
    ratingCount: 203,
    fabric: "Lacquered Wood",
    occasion: "Daily",
    segment: "Home",
    rawMaterials: "Wood",
    pattern: "Solid",
    work: "Hand Turned",
    suitableFor: "Home Decor",
    customizable: "No",
  },
  {
    id: 7,
    title: "Kalamkari Hand-Painted Cotton Jacket",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    category: "clothing",
    price: 2749,
    rating: 2.1,
    ratingCount: 430,
    isOutOfStock: true,
    fabric: "Kalamkari Cotton",
    occasion: "Casual",
    segment: "Women",
    rawMaterials: "Cotton",
    pattern: "Kalamkari",
    work: "Hand Painted",
    suitableFor: "Outerwear",
    customizable: "No",
  },
  {
    id: 8,
    title: "Sheesham Wood Travel Desk Organiser",
    image: "https://fakestoreapi.com/img/71IBHvO7uvL._AC_UY879_.jpg",
    category: "accessories",
    price: 1999,
    rating: 4.7,
    ratingCount: 500,
    fabric: "Sheesham Wood",
    occasion: "Travel",
    segment: "Unisex",
    rawMaterials: "Wood",
    pattern: "Grain",
    work: "Carved",
    suitableFor: "Travel",
    customizable: "Yes",
  },
  {
    id: 9,
    title: "Pashmina Blend Shawl-Collar Coat",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    category: "clothing",
    price: 5499,
    rating: 4.7,
    ratingCount: 500,
    fabric: "Pashmina Blend",
    occasion: "Formal",
    segment: "Women",
    rawMaterials: "Wool",
    pattern: "Solid",
    work: "Tailored",
    suitableFor: "Outerwear",
    customizable: "No",
  },
  {
    id: 10,
    title: "Meenakari Enamel Pendant Necklace",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelery",
    price: 2299,
    rating: 4.2,
    ratingCount: 140,
    isNew: true,
    fabric: "Gold Plated Brass",
    occasion: "Festive",
    segment: "Women",
    rawMaterials: "Brass",
    pattern: "Meenakari",
    work: "Enamelled",
    suitableFor: "Gifting",
    customizable: "No",
  },
  {
    id: 11,
    title: "Handwoven Bhagalpur Jute Floor Rug",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    category: "home",
    price: 3299,
    rating: 3.8,
    ratingCount: 90,
    fabric: "Jute",
    occasion: "Daily",
    segment: "Home",
    rawMaterials: "Jute",
    pattern: "Woven Stripes",
    work: "Handloom",
    suitableFor: "Home Decor",
    customizable: "No",
  },
  {
    id: 12,
    title: "Khurja Blue Pottery Chai Set",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    category: "home",
    price: 1749,
    rating: 4.0,
    ratingCount: 110,
    isNew: true,
    fabric: "Glazed Ceramic",
    occasion: "Daily",
    segment: "Home",
    rawMaterials: "Clay",
    pattern: "Blue Pottery",
    work: "Wheel Thrown",
    suitableFor: "Kitchen",
    customizable: "No",
  },
];
