/**
 * Regenerates lib/fallback-products.ts from the live FakeStoreAPI catalogue so
 * the fallback stays in sync with the API (titles, prices, categories).
 * Product images are pointed at local files in /public/products/<id>.png.
 *
 * Run with: node --experimental-strip-types scripts/gen-fallback.ts
 */
import { writeFileSync } from "node:fs";
import { decorateProduct } from "../lib/products.ts";

type Raw = {
  id: number;
  title: string;
  price: number;
  category: string;
  image: string;
  rating?: { rate: number; count: number };
};

const response = await fetch("https://fakestoreapi.com/products", {
  headers: { "User-Agent": "Mozilla/5.0", Accept: "application/json" },
});

if (!response.ok) {
  console.error(`FakeStoreAPI responded with ${response.status}`);
  process.exit(1);
}

const raw = (await response.json()) as Raw[];
const products = raw.map((item) => decorateProduct(item)).map((p) => ({ ...p, image: `/products/${p.id}.png` }));

const header = `import type { Product } from "@/types/product";

/**
 * Deterministic fallback catalogue. Used when FakeStoreAPI is unreachable so
 * the page always renders a complete, stable product listing.
 * Prices are in INR (₹). Images are local files under /public/products/.
 *
 * Generated by scripts/gen-fallback.ts — do not edit by hand.
 */
export const FALLBACK_PRODUCTS: Product[] = `;

const body = JSON.stringify(products, null, 2).replace(/"([a-zA-Z]+)":/g, "$1:");
writeFileSync("lib/fallback-products.ts", `${header}${body};\n`);

console.log(`Wrote ${products.length} fallback products with local images.`);
